#!/bin/bash

# Have to do 2.5 first, because 2.4 will write a blank description if there
# isn't one already!

/cygdrive/c/Program\ Files/Python25/python.exe setup.py bdist_egg sdist upload
/cygdrive/c/Program\ Files/Python24/python.exe setup.py bdist_egg upload
